# Generated by Django 4.2 on 2024-10-19 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="тема сообщения"),
                ),
                ("body", models.TextField(verbose_name="текст сообщения")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="дата первой отправки"),
                ),
                ("end_date", models.DateTimeField(verbose_name="дата завершения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("завершена", "Completed"),
                            ("создана", "Created"),
                            ("запущена", "Running"),
                        ],
                        default="создана",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "regularity",
                    models.CharField(
                        choices=[
                            ("ежедневно", "Daily"),
                            ("еженедельно", "Weekly"),
                            ("ежемесячно", "Monthly"),
                        ],
                        max_length=15,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter",
                        to="newsletter.message",
                        verbose_name="сообщение",
                    ),
                ),
                (
                    "recipient",
                    models.ManyToManyField(
                        related_name="recipients",
                        to="clients.client",
                        verbose_name="получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["status", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="DistributionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_try",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Успешно", "Successful"),
                            ("Не успешно", "Unsuccessful"),
                        ],
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="ответ сервера")),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="newsletter.newsletter",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["-last_try"],
            },
        ),
    ]
