# Generated by Django 4.2 on 2024-10-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="эл.почта")),
                ("last_name", models.CharField(max_length=50, verbose_name="фамилия")),
                ("first_name", models.CharField(max_length=50, verbose_name="имя")),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="отчество"),
                ),
                ("comment", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ["last_name"],
                "permissions": [],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["last_name"], name="clients_cli_last_na_392efd_idx"
            ),
        ),
    ]
