# Generated by Django 4.2 on 2024-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["last_name"], name="clients_cli_last_na_392efd_idx"
            ),
        ),
    ]
