# Generated by Django 4.2 on 2024-10-17 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("body", models.TextField(verbose_name="содержимое")),
                (
                    "image",
                    models.ImageField(
                        upload_to="blog/%Y/%m/%d/", verbose_name="изображение"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество  просмотров"
                    ),
                ),
                (
                    "publish",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            17,
                            17,
                            37,
                            59,
                            571452,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="дата публикации",
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["-publish"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-publish"], name="blog_articl_publish_2a54df_idx"
            ),
        ),
    ]
