# Generated by Django 4.2 on 2024-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="blog/", verbose_name="изображение"),
        ),
    ]
